# Generated by Django 3.2.4 on 2021-12-03 06:26

from django.db import migrations


def migrate_images(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    ProductImage = apps.get_model('shop', 'ProductImage')

    for product in Product.objects.all():
        product_image = ProductImage(product=product, image=product.image)
        product_image.save()
        product.image.delete(save=True)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211203_0625'),
    ]

    operations = [
        migrations.RunPython(migrate_images)
    ]
